[program:thulium-bridge]
command=/usr/bin/php /opt/thulium-bridge/bin/thulium-bridge run-loop
directory=/opt/thulium-bridge
autostart=true
autorestart=true
stopsignal=TERM
stopwaitsecs=20
stderr_logfile=/var/log/thulium-bridge.err.log
stdout_logfile=/var/log/thulium-bridge.out.log
user=www-data
